### ISSUE TITLE
How to use with HashRouter?

### ISSUE THREAD

**Issue by sheam** [alisd23/mobx-react-router#20]
I would like to use this with the HashRouter, otherwise I lose my location on a page refresh. But HashRouter doesn't not take a history property, so I don't think it is possible to set this up with mobx-react-router?

**Comment by alisd23** [comment]
Hey you should just be able to switch out browserHistory for hashHistory like so:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import createHashHistoryfrom 'history/createHashHistory';
import { Provider } from 'mobx-react';
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import { Router } from 'react-router';
import App from './App';

const hashHistory= createHashHistory();
const routingStore = new RouterStore();

const stores = {
  // Key can be whatever you want
  routing: routingStore,
  // ...other stores
};

const history = syncHistoryWithStore(hashHistory, routingStore);

ReactDOM.render(
  <Provider {...stores}>
    <Router history={history}>
      <App />
    </Router>
  </Provider>,
  document.getElementById('root')
);
```

You shouldn't need the specific router implementations, just the generic `Router` component from react-router v4.

**Comment by sheam** [comment]
Thanks, I really appreciate the response. Your suggestion worked great.
