### ISSUE TITLE
Using Browser buttons, gets rendered page out of sync with path

### ISSUE THREAD

**Issue by sheam** [alisd23/mobx-react-router#22]
My routing seems to work fine. But when I use the browser 'back' button, the URL changes correctly, but the page then doesn't match the URL. The first time I hit the back button, nothing happens. Then second time I click it goes to where it should have gone the first time.

This is my entry point: index.tsx:
```
 {UserStore} from './data/stores/UserStore';
declare let module: any;

import * as React from "react";
import * as ReactDOM from "react-dom";
import {AppContainer} from 'react-hot-loader';
import { Router } from 'react-router';
// import createHistory from 'history/createBrowserHistory';
import createHistory from 'history/createHashHistory';
import { Provider } from 'mobx-react';
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import { App } from "./components/app/App";

const history = createHistory();
const routingStore = new RouterStore();
const users = new UserStore();
const synchronizedHistory = syncHistoryWithStore(history, routingStore);
const stores = {
    routing: routingStore,
    users: users
};

const renderApp = (Component: any) =>
{
    ReactDOM.render(
        <AppContainer>
            <Provider {...stores}>
                <Router history={synchronizedHistory}>
                    <Component />
                </Router>
            </Provider>
        </AppContainer>,
        document.getElementById("app_content")
    );
};

renderApp(App);

// Hot Module Replacement API
if (module.hot) {
    module.hot.accept('./components/app/App', () => {
        renderApp(App)
    });
}
```

My app file:
```
import 'bootstrap';
import * as React from 'react';
import {TopNav} from '../topnav/TopNav';
import {History} from 'history';
import {Routes} from './Routes';
import {inject, observer} from 'mobx-react';
import {UserStore} from '../../data/stores/UserStore';
import {Level, Logger} from '../../util/Logger';

interface IAppProps { routing: History, users: UserStore }

@inject('routing')
@observer
export class App extends React.Component<IAppProps, undefined>
{
    //noinspection JSMethodCanBeStatic,JSUnusedLocalSymbols
    private log(msg: string, level?: Level): void
    {
        Logger.get().log(msg, 'App', level || Level.TRACE);
    }

    render(): JSX.Element
    {
        const { location } = this.props.routing;
        return (
            <div>
                <TopNav/>
                <div className='container body-content'>
                    <Routes/>
                    <div className='small'>path: {location.pathname}</div>
                </div>
            </div>);
    }
}
```

My routes file:
```
import * as React from 'react';
import {Route, Switch} from 'react-router-dom';
import {HomePage, PageOne, PageThree, PageTwo} from '../home/HomePage';
import {PendingDeliveryPage} from '../delivery/PendingDeliveryPage';
import {DeliveryExecutePage} from '../delivery/DeliveryExecutePage';


export class Routes extends React.Component<undefined, undefined>
{
    public render(): JSX.Element
    {
        return (
            <Switch>
                <Route exact path='/' component={HomePage} />
                <Route path='/delivery/:id/execute' component={DeliveryExecutePage} />
                <Route path='/delivery' component={PendingDeliveryPage} />
                <Route path='/one' component={PageOne} />
                <Route path='/two' component={PageTwo} />
                <Route path='/three' component={PageThree} />
            </Switch>
        );
    }
}
```

And lastely my test pages:
```
import * as React from "react";
import {Link, RouteComponentProps} from 'react-router-dom';

export class HomePage extends React.Component<RouteComponentProps<any>, undefined>
{
    public render(): JSX.Element
    {
        return (
            <div>
                <h1>Home</h1>
                <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/one">One</Link></li>
                    <li><Link to="/two">Two</Link></li>
                    <li><Link to="/three">Three</Link></li>
                </ul>
            </div>);
    }
}

export class PageOne extends React.Component<RouteComponentProps<any>, undefined>
{
    public render(): JSX.Element
    {
        return (
            <div>
                <h1>Page One</h1>
                <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/one">One</Link></li>
                    <li><Link to="/two">Two</Link></li>
                    <li><Link to="/three">Three</Link></li>
                </ul>
            </div>);
    }
}

export class PageTwo extends React.Component<RouteComponentProps<any>, undefined>
{
    public render(): JSX.Element
    {
        return (
            <div>
                <h1>Page Two</h1>
                <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/one">One</Link></li>
                    <li><Link to="/two">Two</Link></li>
                    <li><Link to="/three">Three</Link></li>
                </ul>
            </div>);
    }
}

export class PageThree extends React.Component<RouteComponentProps<any>, undefined>
{
    public render(): JSX.Element
    {
        return (
            <div>
                <h1>Page Three</h1>
                <ul>
                    <li><Link to="/">Home</Link></li>
                    <li><Link to="/one">One</Link></li>
                    <li><Link to="/two">Two</Link></li>
                    <li><Link to="/three">Three</Link></li>
                </ul>
            </div>);
    }
}
```

You can click 

1. Start at 'Home'
2. Click 'One'
3. Click 'Two'
4. Click 'Three', and everthing should be fine.
5. Click Browser Back, path changes to /two, but page does not render anything new.
6. Click Browser Back and path changes to /one, and now page /two renders.
7. Click Browser Back and page changes to /, but page /one renders.
8. etc.

Am i doinng something wrong here?

**Comment by sheam** [comment]
It seems I have the same problem using createBrowserHistory() as with createHashHistory().

I have also found that push('/one') doesn't really work either. It changes url, but page /one doesn't render.

**Comment by alisd23** [comment]
Hmm this seems strange - this might actually be an issue with the library, I'll have to look into it this weekend. Unless someone else wants to give it a go - feel free!

**Comment by sheam** [comment]
Love to help, but am drowning in my learning of React+Mobx right now as it is. :)

**Comment by anupshinde** [comment]
@alisd23 The problem seems to be with the way RR4 works. However, the examples could use correction.

@sheam Use `withRouter` to wrap the components that use `<Route...>`

https://reacttraining.com/react-router/web/api/withRouter

```
import { withRouter } from 'react-router'
```



Instead of 

```
export class Routes extends React.Component<..., ...> {...}
```

Use:

```
class Routes_ extends React.Component<..., ...> {...}

export const Routes  = withRouter(Routes_)

---OR---

@withRouter
export class Routes extends React.Component<..., ...> {
  ...
}
```

> That should also fix the problem with `setTimeout` i.e. if it was actually required.

**Comment by sheam** [comment]
Thanks for the tip. I wrapped Routes with a withRouter, as I couldn't figure out how to make the compiler happy using the decorator.

Backforward navigation is still broken, however the setTimeout issue is solved.

**Comment by alisd23** [comment]
So I did some research, and I'm pretty sure this is a react-router or mobx-react issue. Even with this extremely simple case the components do not correctly re-render on the back button - *however* the location value in the mobx-react-router store *is updating* as the path is changing in the App component.

```jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { observe } from 'mobx';
import createBrowserHistory from 'history/createBrowserHistory';
import { inject, observer, Provider } from 'mobx-react';
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import { Router } from 'react-router'
import { Switch, Route } from 'react-router-dom'

const browserHistory = createBrowserHistory();
const routingStore = new RouterStore();

const stores = {
  // Key can be whatever you want
  routing: routingStore,
};

const history = syncHistoryWithStore(browserHistory, routingStore);

class App1 extends Component {
  render() {
    const { location, push, goBack } = this.props.routing;
    console.log('App render')

    return (
      <div>
        <span>Current pathname: {location.pathname}</span>
        <button onClick={() => push('/test')}>Go to test</button>
        <button onClick={() => push('/')}>Go home</button>
        <button onClick={() => goBack()}>Go Back</button>
        <h4>{Math.random()}</h4>
        <Switch>
          <Route path='/' exact component={() => <h1>HOME</h1>} />
          <Route component={() => <h1>404</h1>} />
        </Switch>
      </div>
    );
  }
}

const App = inject('routing')(observer(App1));

ReactDOM.render(
  <Provider {...stores}>
    <Router history={history}>
      <App />
    </Router>
  </Provider>,
  document.getElementById('root')
);
```

I think this needs bringing up with one of those projects - with a really similar simple example like this.
I'll leave the issue while this is still an issue as a warning to people.

**Comment by sheam** [comment]
How is it that I am the first person to come across this? Any I doing something non-standard? What am I doing different than your example?

**Comment by alisd23** [comment]
Maybe the switch element is the issue. As in my example the App component does render when the route changes (including back button) however the switch just doesn't change the component.

**Comment by alisd23** [comment]
However I didn't try it without the switch.

**Comment by sheam** [comment]
In your Readme example, how do the different pages render without a Switch?

In your example above, are you seeing the same behaviour as I then?

What is the work around for this then?

**Comment by alisd23** [comment]
Ok after more investigating it looks like a react-router problem, but not with the switch - with the `Route` component system. The Route component uses context to get the current location, and I think the `shouldComponentUpdate` of the mobx-react `observer` component (which wraps App in your example) is returning false. This in turn is messing up the context update.

Context is known to be a fairly broken feature, especially when pairing with MobX/Redux, which overwrite `shouldComponentUpdate` in places.

This needs bringing up with the `react-router` guys.

In terms of a workaround - wrapping `App` (the component which uses mobx `observer`) works for me, as it will return false from `shouldComponentUpdate`.

**Comment by sheam** [comment]
Ali,

I appreciate all your help. Sorry to be daft, but wrap the App component in what?

My app currently looks like this:

index:
```
const renderApp = (Component: any) =>
{
    ReactDOM.render(
        <AppContainer>
            <Provider {...stores}>
                <Router history={synchronizedHistory}>
                    <Component />
                </Router>
            </Provider>
        </AppContainer>,
        document.getElementById('app_content')
    );
};

renderApp(App);
```

```
@inject('routing')
@observer
export class App extends React.Component<IAppProps, undefined>
{
    render(): JSX.Element
    {
        const { location } = this.props.routing;
        return (
            <div>
                <TopNav/>
                <div className='container body-content'>
                    <Routes/>
                    <div className='small hidden'>path: {location.pathname}</div>
                </div>
                <DevTools/>
            </div>);
    }
}
```
ana my Routes looks like this:
```
class _Routes extends React.Component<any, undefined>
{
    public render(): JSX.Element
    {
        return (
            <Switch>
                <Route exact path='/' component={HomePage} />
                <Route path='/delivery/:id/execute' component={DeliveryExecutePage} />
                <Route path='/delivery' component={PendingDeliveryPage} />
            </Switch>
        );
    }
}

export default withRouter(_Routes)
```

It is more broken up than your example, but I think it is the same structure...

**Comment by sheam** [comment]
Thank you! That solved it for me. I was wrapping my Routes class. Wrapping the app class fixed it.

**Comment by wallysson-hotmart** [comment]
Sorry guys, but i'm currently having the same issue and can't find a way to solve it. I need to wrap my entire app with ```withRouter```?

I din't understood this how to solve this problem.

**Comment by alisd23** [comment]
You probably need to wrap any components which render `<Route />` components in the `withRouter` higher order component. That's the easiest fix. Again I don't see what can be done from this packages point of view is the issue comes from react-router using the unstable `context` API.

**Comment by erasmo-marin** [comment]
It doesn't make sense to use mobx-react-router if we have to do this in every route component, is there any other real solution?

**Comment by alisd23** [comment]
There are a few potential solutions listed here:
https://reacttraining.com/react-router/web/guides/dealing-with-update-blocking

I guess which solution you use depends on the project

**Comment by wallynm** [comment]
Sory about bring this discussion again, turns out that i've discovered a problem that i had im my configuration and this maybe should help someone!

When you sync
```js
const History = syncHistoryWithStore(browserHistory, Stores.RouterStore);
```

Your base route already initialized with browser routing, so youre ready to create your routes and access them. My problem was in my startup React component:

```js
class App extends Component {
  render() {
    return (
      <Provider {...Stores}>
        <Router history={History}>
          <BrowserRouter>    
            <Routing/>
          </BrowserRouter>
        </Router>
      </Provider>
    )
  }
}
```

I had my `Router={history}` and also my `<BrowserRouter>` again, and this was making all the tree not work properly, after removing `BrowserRouter` from the tree and allowing my synced state handle the routing solved the problem!

Was a silly mistake because once you learn how to configure V4 routing and you plug this component together everything works fine, but turns out that two histories are trying to control the app state but just one really works making the plugin not work as intend.

Well, at the end just removing `BrowserRouter` and let the plugin do his job with `syncHistoryWithStore` solved my issues! Thanks.

**Comment by ricardovf** [comment]
I fixed it here using:

````
window.stores = window.stores || store;

const history = syncHistoryWithStore(browserHistory, window.stores.routing);

const renderApp = Component => {
  ReactDOM.render(
    <AppContainer>
      <Provider {...window.stores}>
        <Router
          basename={__DEV__ ? undefined : '/knox-wallet-ui'}
          history={history}
        >
          <Component />
        </Router>
      </Provider>
    </AppContainer>,
    document.getElementById('root')
  );
};
// registerServiceWorker();

renderApp(withRouter(App));

// hot reload config
if (module.hot) {
  module.hot.accept(['./App', './store'], () => {
    const newApp = require('./App').default;
    // store.deviceStore._forceRefresh();
    renderApp(withRouter(newApp));
  });
}
````

And the component that has the Switch uses:
`````
@withStyles(styles)
@inject('appStore', 'deviceStore', 'routing')
@withRouter
@observer
export default class AppLayout extends React.Component {
`````

Thanks for this lib, it's great.
