### ISSUE TITLE
An Example App?

### ISSUE THREAD

**Issue by chobo2** [alisd23/mobx-react-router#26]
Hi

I am wondering if there is some sample app? I followed the usage but I am confuse what  "push(/test)" is. Is that another component or what?

**Comment by alisd23** [comment]
`push('/test')` is changing the current url to `/test`. Simple as that.

**Comment by chobo2** [comment]
I do see the url changing but it was not clear that I have to use the Route to actually make something happen.

I am still running into issues when "push" is in a component and "route" is in another component. 

I have something like the following.

```
import plannerStore from './PlannerStore';
import { RouterStore } from 'mobx-react-router';

const routingStore = new RouterStore();

const stores = {
    plannerStore,
    routingStore
}

export default stores;

import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'mobx-react';
import { useStrict } from 'mobx';

import createBrowserHistory from 'history/createBrowserHistory';
import { syncHistoryWithStore } from 'mobx-react-router';
import { Router } from 'react-router';

import App from './App';

import PlannerComponent from './components/PlannerComponent';

const browserHistory = createBrowserHistory();

import stores from './stores/index';

const history = syncHistoryWithStore(browserHistory, stores.routingStore);

useStrict(true);

ReactDOM.render(
    <Provider {...stores}>
        <Router history={history}>
            <PlannerComponent />
        </Router>
    </Provider>,
    document.getElementById('root')
);

import React, {Component} from 'react'
import ReactDOM from 'react-dom';
import {observer, inject} from 'mobx-react';

import CourseComponent from './CourseComponent';
import GradeComponent from './GradeComponent'

import { Route } from 'react-router';

@inject('plannerStore', 'routingStore')
@observer
export default class PlannerComponent extends Component {
    constructor() {
        super();
    }
    render() {

        return (
            <div>
                <CourseComponent />
                <Route path='/grade' component={GradeComponent}/>
            </div>
        )
    }
}

import React, {Component} from 'react'
import ReactDOM from 'react-dom';
import {observer, inject} from 'mobx-react';

import planner from '../styles/planner.scss'

@inject('plannerStore', 'routingStore')
@observer
export default class CourseComponent extends Component {
    constructor() {
        super();
    }
    render() {
                const { location, push, goBack } = this.props.routingStore;
        return (
            <div >
                 <button onClick={() => push('/grade')}>grades</button>
            </div>
        )
    }
}
```

**Comment by alisd23** [comment]
I assume this is the same issue as #22, read that issue - it's basically an issue with react-router which we have to workaround with `withRouter`.

**Comment by alisd23** [comment]
Also I doin't know why you're wrapping `PlannerComponent` in `@inject` and `@observer`. That component doesn't even use any state from the stores. Remove that and you shou;dn't need the `withRouter` fix.

**Comment by chobo2** [comment]
Hey, so all my problems seem to be related with not using withRouter? I understand what you mean with not using inject in PlannerComponent but I thought it was always recommended to use @observer even in the  most simplest  components. I also not sure why removing both those would solve my problem.

This is for a learning, as my real Planner component does use the stuff(I just stripped down to basic levels to make things easier for people to see my problem).

With withRoute do I have to just do` export default class withRouter(CourseComponent) extends Component `

**Comment by chobo2** [comment]
Also one more thing I noticed is if someone would refresh the page or type in "http://localhost:8080/grade" they get "Cannot GET /grade" will this be fixed withRouter? or do I need something else to handle that situation?

**Comment by alisd23** [comment]
`observer` and `inject` are only needed for components which require something out of the mobx stores. But this is a `mobx` issue, nothing to do with this library.

The `cannot GET` issue would be nothing to do with this library also. That would be to do with how you're building/serving your project. 

Keep in mind this library is only for storing the current routing state in a mobx store - bridging together `react-router` and `mobx` - so you may not need it. Make sure you understand react-router and mobx first.
