### ISSUE TITLE
how to define other store?

### ISSUE THREAD

**Issue by yangxiaolin** [alisd23/mobx-react-router#35]
<pre>
  const stores = {
    // Key can be whatever you want
    routing: routingStore,
    // ...other stores
  };
</pre> 
 this code . but how to define other stores?  has any doc. thank you

**Comment by Skaronator** [comment]
```
  const stores = {
    routing: routingStore,
    auth: authStore,
    ui: uiStore,,
    form: formStore,,
  };
```
