### ISSUE TITLE
Is it possible to use this along with mobx-state-tree?

### ISSUE THREAD

**Issue by dbertella** [alisd23/mobx-react-router#37]
I'm trying to change location from an action in mobx state tree, is it possible to use this router with it?
In case is there any example on how to add the RouterStore as a model in mst?

I opened a similar issue in mobx-state-tree with more details, let's see if someone can respond there: https://github.com/mobxjs/mobx-state-tree/issues/665

**Comment by alisd23** [comment]
Hi, I'm not too sure as I have not used mobx-state-tree before, but I would hope there would be some way of incorporating other 3rd party libraries into it.

I've commented on the other issue (in the mobx-state-tree repo). Will probably keep the conversation going there as I see this as potentially more of an interoperability issue with mobx-state-tree.

**Comment by alisd23** [comment]
Closing for now as the discussion can stay on mobxjs/mobx-state-tree#665.
