### ISSUE TITLE
get error history.getCurrentLocation is not a function()

### ISSUE THREAD

**Issue by optimatex** [alisd23/mobx-react-router#4]
Hi. Thanks for ur package. I get this error and don't know how to handle it 
`TypeError: history.getCurrentLocation is not a function(…)`
any ideas?

**Comment by alisd23** [comment]
No problem. So this package now requires react-router v3, which uses the new `history` package version. I think `history.getCurrentLocation` has been replaced by just `history.location` - https://github.com/mjackson/history#usage

**Comment by optimatex** [comment]
i was trying to change ` history.getCurrentLocation`  to `history.location()` in `mobx-react-router.js:268 ` but got similar error `TypeError: history.location is not a function(…)`
maybe my react-router package is not 3.0.0. `npm list` shows that i have `+-- UNMET PEER DEPENDENCY react-router@2.8.1` cuz in my package.json there is "mobx-react-router": "^3.0.0", and i put `npm update react-router@3.0.0`

**Comment by alisd23** [comment]
Just checking the code history.getCurrentLocation will still work with v3. Yeah I think it's because you have react-router v2. I decided to only support v3 as there aren't really any major changes from v2, just bug fixes.
Maybe try upgrade to v3?

**Comment by alisd23** [comment]
What version of **this** package have you got installed?

**Comment by optimatex** [comment]
mobx-react-router@3.0.0

**Comment by optimatex** [comment]
don't know how to update this UNMET PEER DEPENDENCY react-router@2.8.1 cuz i did all standart npm update methods

**Comment by alisd23** [comment]
Try `rm node_modules/react-router -fr && npm install`

**Comment by alisd23** [comment]
If you're on unix.

**Comment by optimatex** [comment]
i have used this `rm node_modules/react-router -fr && npm install` and now npm list --depth=0 shows react-router@3.0.0. It seems that problem is solved. Need to fix few more bugs from refactoring code and i'll notify very soon
Any way thank u for ur support!

**Comment by alisd23** [comment]
No problem good luck :+1:

**Comment by JohnLouderback** [comment]
@alisd23 I'm having the same issue, however the steps above do not resolve the issue for me. I am seeing `UNMET PEER DEPENDENCY mobx@3.0.2` despite that module being installed and in the package.json. I even deleted a fresh installed all my node modules.

**Comment by JohnLouderback** [comment]
This may be relevant mjackson/history#402

**Comment by alisd23** [comment]
@JohnLouderback  Ah I didn't realise mobx released a new major version. This library still has a peer dependency on v2.5.2, so I wonder if that's the issue. I'll investigate.

**Comment by alisd23** [comment]
Hmm History v3 *definitely* has `getCurrentLocation` on it. And react-router depends on history v3, so are you definitely using react-router `v3`?

**Comment by JohnLouderback** [comment]
`npm list --depth=0` shows `+-- react-router@3.0.0` When I set a break point at the method call in the `mobx-react-router` module to `getCurrentLocation` That's where (as seen in the screenshot above) the history object does not have that method defined on it. Perhaps its something with the way I have everything initialized. Here's the module where the history object is set up:
```typescript
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Router, browserHistory } from 'react-router';
import getRoutes from './routes';
import { Provider } from 'mobx-react';
import { observable, extendObservable } from 'mobx'
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import ApiClient from './helpers/ApiClient';

const clone = (obj : Object) : Object => JSON.parse(JSON.stringify(obj))
const client = new ApiClient();
const routingStore = new RouterStore();
const stores = window['stores'] = observable({
  ...clone(window['__data']),
  routes: routingStore
});
const history = syncHistoryWithStore(browserHistory, routingStore);

ReactDOM.render(
  <Provider {...stores}>
    <Router history={history}>
      {getRoutes(stores)}
    </Router>
  </Provider>,
  document.getElementById('content')
);

```

If there's anymore information I can provide you with to help troubleshoot the issue, let me know.

**Comment by JohnLouderback** [comment]
Ah, so when I run `npm show history version` it outputs `4.5.1`. I wonder if the problem isn't that react-router is set up to install whatever the newest version is of the history module.

**Comment by JohnLouderback** [comment]
Okay, so that was in fact the issue. Running  `rm node_modules/history -fr && npm install history@3.0.0` fixed the issue. I would say, it would good if this package has a fall forward for the latest `history` package.

**Comment by rokoroku** [comment]
@JohnLouderback Seems weird, `react-router` v3 has its own dependency as `history` ^3.0.0 
(see [react-router/package.json#L36](https://github.com/ReactTraining/react-router/blob/master/package.json#L36))

The module `history` always have breaking changes in major updates, so it's important to keeping major version to its dependencies. Try to inspect if other dependencies install the latest version of the history module.

**Comment by alisd23** [comment]
@JohnLouderback Yeah the react-router peer dependency should be enough to guarantee that history `v3` is installed. Looks like history was upgraded to `v4` somehow...

Either way glad it's working now!

**Comment by JohnLouderback** [comment]
Thanks for the help!
