### ISSUE TITLE
New react-router typings causes mismatch with mobx-react-router

### ISSUE THREAD

**Issue by JReinhold** [alisd23/mobx-react-router#43]
## The issue

The typings for react-router was updated in March 2018, with this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24168

That has created a slight mismatch in typings for the `history` object in react-router and mobx-react-router. react-router now states that the history prop cannot be `undefined` / `null`, (which is correct, `<Router>` says that `history` is required). However the history returned from the `RouterStore` by mobx-react router has the possibility to be undefined. So now we need to check if `history` is defined or not every time we pass it to a `<Router>` component, which is not ideal.

Judging by the source code in `sync.js` it does really seem like the history property in `RouterStore` is undefined, until `syncHistoryWithStore` has been called.

## Current workaround

I've created a `RouterStoreSynchronized` class that extends from `RouterStore` but explicitly sets the `history` and `location` properties to exist. I know they do, because I call `syncHistoryWithStore` immediately after creation.

```typescript
export class RouterStoreSynchronized extends RouterStore {
	history!: History;
	location!: Location;
}

const browserHistory = createBrowserHistory();
export const routerStore = new RouterStoreSynchronized();
syncHistoryWithStore(browserHistory, routerStore);
```

## Possible long-term solutions

1. require all TypeScript users to do `routerStore.history!` every time, instead of just `routerStore.history`. This feels annoying to me.
2. Make `syncHistoryWithStore()` return both `SynchronizedHistory` and a `SynchronizedRouterStore`, that we use instead of the default `RouterStore`. We always know that `history` and `location` are present after `syncHistoryWithStore()`, so we can safely return a `SynchronizedRouterStore` in that function, and make the user refer to that instance everywhere.
3. Completely replace the current API with a single function, `createRouterStore()`, that takes a `history` object, and returns a pre-synchronized `RouterStore`, eliminating the need to run `syncHistoryWithStore`. At the moment, a `RouterStore` that hasn't been synced is useless anyway, so it seems a bit weird that we are required to do the two step process of instantiating a `RouterStore` and then synchronizing it. This new API could look something like:
```javascript
const browserHistory = createBrowserHistory();
const routingStore = createRouterStore(browserHistory); //synchronization handled in function

const stores = {
  // Key can be whatever you want
  routing: routingStore,
  // ...other stores
};

ReactDOM.render(
  <Provider {...stores}>
    <Router history={routingStore.history}> // get history from RouterStore
      <App />
    </Router>
  </Provider>,
  document.getElementById('root')
);
```
Instead of a `createRouterStore()` function, it could just be part of the `RouterStore` constructor, ie. `new RouterStore(browserHistory)`, it would result in the same.

What are your thoughts on all of this?
Let me know if you would like a PR with any of this.

**Comment by alisd23** [comment]
Hey thanks for the issue (and for the great detail) - good find.

My first question is: what is the case for passing the history property from a `RouterStore` instance in to a `Router` component, as opposed to just passing the return history value from `syncHistoryWithStore` as the README example does? i.e:

```js
const browserHistory = createBrowserHistory();
const routingStore = new RouterStore();

const stores = {
  // Key can be whatever you want
  routing: routingStore,
  // ...other stores
};

const history = syncHistoryWithStore(browserHistory, routingStore);

ReactDOM.render(
  <Provider {...stores}>
    <Router history={history}>
      <App />
    </Router>
  </Provider>,
  document.getElementById('root')
);
```
Maybe I'm missing a use case.

But in general I think your current workaround is the correct implementation anyway - meaning the `history` and `location` properties should be **required** in the typings:

```ts
export class RouterStore {
  history: History;
  location: Location;
}
```

Would this solve the problem?

Even though **technically** those properties *can* be undefined/null, using this library as described in the docs would mean that any useful application of using the a `RouterStore` would be in situation where the history and location properties **have** been set (at any point after the `syncHistoryWithStore` function call).

**Comment by alisd23** [comment]
Added in release 4.0.3
