### ISSUE TITLE
Any way to update a hash route?

### ISSUE THREAD

**Issue by vertic4l** [alisd23/mobx-react-router#51]
Got the following issue:
`{domain}{?someParams}#/{route}`

That's my url, i need to update `{?someParams}` while preserving `#/{route}`.

Is there any elegant way for doing this?

Edit:
Right now i get:

`{domain}{?someParams}#/{route}{?someParams}`

when i try to replace it.

**Comment by vertic4l** [comment]
Would something like `createHashHistory({queryKey: false})` although it's no possible option right now?

**Comment by alisd23** [comment]
Does this issue exist without `mobx-react-router` too?
