### ISSUE TITLE
update peer dependencies

### ISSUE THREAD

**Issue by leantide** [alisd23/mobx-react-router#55]
When using with mobx@^5.0.0 npm gives following warning:

npm WARN mobx-react-router@4.0.4 requires a peer of mobx@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

Can the peer dependencies of mobx-react-router in the package.json file be updated to reflect its compatibility with mobx 5?

**Comment by alisd23** [comment]
New version (`4.0.5`) released with this fix, thanks again @leantide.
