### ISSUE TITLE
n element descriptor's .kind property must be either “method” or “field”

### ISSUE THREAD

**Issue by JamesTheHacker** [alisd23/mobx-react-router#59]
I'm following the documentation for [`mobx-react-router`](https://github.com/alisd23/mobx-react-router) but upon attempting to run my application I get the following error in the browser:

    Uncaught TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "undefined"
        at _toElementDescriptor (app.js:49988)
        at _toElementFinisherExtras (app.js:49990)
        at _decorateElement (app.js:49980)
        at app.js:49976
        at Array.forEach (<anonymous>)
        at _decorateClass (app.js:49976)
        at _decorate (app.js:49958)
        at Module../src/App/UserStore.js (app.js:50012)
        at __webpack_require__ (bootstrap:19)
        at Module../src/index.js (index.js:1)

Here is how I intitialize: 

    const appContainer = document.getElementById('app');
    if(appContainer) {
      const browserHistory = createBrowserHistory()
      const routingStore = new RouterStore();
    
      const stores = {
        users: userStore,
        routing: routingStore
      }
    
      const history = syncHistoryWithStore(browserHistory, routingStore);
    
      ReactDOM.render(
        (
          <Provider {...stores}>
            <Router history={history}>
              < App />
            </Router>
          </Provider>
        ),
      appContainer);
    }

And this is how I use:

    @inject('routing')
    @inject('users')
    @observer
    class App extends Component { ...

My `UserStore`:

    import { observable, action, computed } from "mobx"
    
    class UserStore {
      @observable users = [];
    
      @action addUser = (user) => {
        this.users.push(user)
      }
    
      @computed get userCount () {
        return this.users.length
      }
    }
    
    const store = new UserStore();
    export default store;

I've tried to Google for this error but it's returning no useful results. Any ideas what I am doing wrong?

**Comment by alisd23** [comment]
Hmm not sure what the issue was there. Seems unlikely to be related to this library though. Will close for now until someone see's this issue again or has more information around it 👍
