### ISSUE TITLE
Issue with TypeScript when trying to use SynchronizedHistory from RouterStore

### ISSUE THREAD

**Issue by Tsury** [alisd23/mobx-react-router#60]
Consider I'm creating my Router like so:

```
import React from 'react';
import { Router } from 'react-router';
import { Provider } from 'mobx-react';
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';
import createHashHistory from 'history/createHashHistory';

const hashHistory = createHashHistory();
const routingStore = new RouterStore();
const history = syncHistoryWithStore(hashHistory, routingStore);

const rootStore = { ...someStores, routingStore }

class Routers extends React.Component {
  render() {
    return (
      <Provider {...rootStore}>
        <Router history={history}>
```

And then in some component I want to inject the `routingStore` and use the `SynchronizedHistory`'s `subscribe` method to do something, like so:

`this.props.routingStore.history.subscribe(() => { ... });`

Since `routingStore` is a `RouterStore`, it has a basic `History`, and not a `SynchronizedHistory`. When I try to use `subscribe` it obviously says `Property 'subscribe' does not exist on type 'History<any>`.

What am I doing wrong here? Is there a generic `RouterStore` type I'm missing with a `History` type that I can use to define `routingStore` with?

**Comment by alisd23** [comment]
Ah interesting. So the `history` object on the `RouterStore` is actually the *raw* history object, i.e. not including the `subscribe/unsubscribe` methods. What you want is the history returned by `syncHistoryWithStore`.

You should be able to get the *synchronized* history from ` the withRouter` HOC provided by `react-router` (https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md), although you will have to cast that as a `SynchronizedHistory` as react router will have it typed as a regular `History` object.
