### ISSUE TITLE
Update Peer Dependency

### ISSUE THREAD

**Issue by leantide** [alisd23/mobx-react-router#63]
react-router now at 5.0.0. Can the peer-dependencies in package.json be updated?

"peerDependencies": {
    "mobx": "^3.0.0 || ^4.0.0 || ^5.0.0",
    "react-router": "4.x" <-----
  }

**Comment by alisd23** [comment]
Ah yes good catch. Not using this library at the moment at work so relying on people like you to spot these kind of things.

**Comment by alisd23** [comment]
Will be fixed with #64

**Comment by alisd23** [comment]
Should be done now. Let me know if there's anything else. Kind of rushed a few other upgrades in there too
