### ISSUE TITLE
Server Side Rendering is broken in v4.0.6

### ISSUE THREAD

**Issue by prontiol** [alisd23/mobx-react-router#65]
v4.0.6 was built with `globalObject` set to `window` instead of `this`, so it doesn't work in Node anymore because `window` is not defined.
I would suggest considering removing webpack completely or switching to rollup, as webpack bootstrap is bigger than the library itself.

**Comment by alisd23** [comment]
Released in `4.0.7`. Thanks @vshuhaiev for fixing this 🥇 👍 🎉
