### ISSUE TITLE
Pass state with RoutingStore.push()

### ISSUE THREAD

**Issue by pulli23** [alisd23/mobx-react-router#70]
The main library (react-router v4) supports adding state to the history, different from parameters and the url):

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/history.md

`push(path, [state])` this can then be read through `location.state`

This is very useful for creating several tools: ie to have a "back" button that works on special keyframes. - the location state would describe where to go to instead of just "back".

I do not see an equivalent with mobx-react-router. Am I missing something?

**Comment by gcattan** [comment]
This is now supported by the library.
